[build-system]
requires = ["setuptools==79.0.1", "wheel", "colorama==0.4.6", "pypandoc_binary==1.15", "PythonExtensionsCollection"]
build-backend = "setuptools.build_meta"

[project]
name = "MicroserviceClewareSwitch"
version = "0.1.2"
description = "Microservice for Cleware USB switch control"
readme = "README.md"
requires-python = ">=3.13"
license = "Apache-2.0"
authors = [
    {name = "Robert Bosch GmbH", email = "todo@bosch.com"}
]
keywords = ["Microservice", "Cleware", "USB Switch"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/test-fullautomation/python-microservice-cleware-switch"
Repository = "https://github.com/test-fullautomation/python-microservice-cleware-switch"

[tool.setuptools]
packages = ["MicroserviceClewareSwitch"]

[tool.setuptools.package-data]
MicroserviceClewareSwitch = ["*.pdf"]
